name: Test iOS build
on:
  pull_request:
    paths:
      - '.github/workflows/ios-build.yml'
      - 'ios/**'
      - 'Common/**'
      - '*.podspec'
      - 'Example/ios/**'
      - 'FabricExample/ios/**'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        working-directory: [Example, FabricExample]
    concurrency:
      group: ios-${{ matrix.working-directory }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ matrix.working-directory }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-${{ matrix.working-directory }}-

      - name: Install Reanimated dependencies
        run: yarn install --frozen-lockfile

      - name: Install app dependencies
        working-directory: ${{ matrix.working-directory }}
        run: yarn install --frozen-lockfile

      - name: Restore Pods from cache
        uses: actions/cache@v2
        id: pods-cache
        with:
          path: |
            ${{ matrix.working-directory }}/ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ matrix.working-directory }}-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-${{ matrix.working-directory }}-

      - name: Install Pods
        working-directory: ${{ matrix.working-directory }}/ios
        run: pod check || pod install

      - name: Build app
        working-directory: ${{ matrix.working-directory }}
        run: npx react-native run-ios
