name: Test iOS build
on:
  pull_request:
    paths:
      - 'ios/**'
      - 'Common/**'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        working-directory: [Example, FabricExample]
    concurrency:
      group: ios-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            **/${{ matrix.working-directory }}/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock', '**/${{ matrix.working-directory }}/yarn.lock') }}
      - name: Install Reanimated dependencies
        run: yarn
      - name: Install app dependencies
        working-directory: ${{ matrix.working-directory }}
        run: yarn
      - name: Install pods
        working-directory: ${{ matrix.working-directory }}/ios
        run: pod install
      - name: Build app
        working-directory: ${{ matrix.working-directory }}
        run: npx react-native run-ios
